library;

import 'dart:async';
import 'dart:io';
import 'dart:math';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:image/image.dart' as image_lib;
import 'package:intl/intl.dart';
import 'package:look_atlas/core/error/failure.dart';
import 'package:look_atlas/core/result/result.dart';
import 'package:look_atlas/core/router/app_routes.dart';
import 'package:look_atlas/core/theme/app_colors.dart';
import 'package:look_atlas/core/theme/app_typography.dart';
import 'package:look_atlas/features/products/di/products_providers.dart';
import 'package:look_atlas/features/products/domain/entities/product_catalog.dart';
import 'package:look_atlas/features/products/domain/repositories/products_repository.dart';
import 'package:look_atlas/features/subscription/di/subscription_access_providers.dart';
import 'package:look_atlas/features/subscription/presentation/controllers/subscription_controller.dart';
import 'package:look_atlas/shared/image_picker/image_picker_providers.dart';
import 'package:look_atlas/shared/image_picker/image_source_sheet.dart';
import 'package:look_atlas/shared/widgets/app_asset_image.dart';
import 'package:look_atlas/shared/widgets/app_bottom_sheet.dart';
import 'package:look_atlas/shared/widgets/app_dialog.dart';
import 'package:look_atlas/shared/widgets/app_dotted_border.dart';
import 'package:look_atlas/shared/widgets/app_dropdown.dart';
import 'package:look_atlas/shared/widgets/app_feature_scaffold.dart';
import 'package:look_atlas/shared/widgets/app_image.dart';
import 'package:look_atlas/shared/widgets/app_outlined_button.dart';
import 'package:look_atlas/shared/widgets/app_snack_bar.dart';
import 'package:look_atlas/shared/widgets/app_text_field.dart';
import 'package:look_atlas/shared/widgets/bar_spinner.dart';
import 'package:look_atlas/shared/widgets/primary_button.dart';
import 'package:look_atlas/shared/widgets/shimmer_box.dart';
import 'package:native_cutout/native_cutout.dart';

part 'controllers/product_calibration_actions.dart';
part 'controllers/product_form_controller.dart';
part 'controllers/products_controller.dart';
part 'dialogs/product_dialogs.dart';
part 'dialogs/product_form_dialog.dart';
part 'models/product_view_model.dart';
part 'screens/product_calibration_screens.dart';
part 'screens/product_reference_crop_screen.dart';
part 'screens/products_page.dart';
part 'widgets/product_calibration_fit_step.dart';
part 'widgets/product_calibration_flow.dart';
part 'widgets/product_calibration_placement_controls.dart';
part 'widgets/product_calibration_steps.dart';
part 'widgets/product_calibration_widgets.dart';
part 'widgets/product_catalog_widgets.dart';
part 'widgets/product_filters.dart';
part 'widgets/product_form_widgets.dart';
